name: Deploy IndustryUI

on:
  push:
    branches:
      - develop

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [14]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false


      - name: Use Node.js ${{ matrix.node }} 🔧
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

      - name: Install Modules 🔧
        run: npm install

      - name: Build 🔧
        run: npm run build-storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
