name: Deploy IndustryUI

on:
  pull_request:
    types: [closed]
    branches:
      - master

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v1

      - name: Install
        if: github.event.pull_request.merged == true
        run: |
          npm install

      - name: Build and Deploy
        if: github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          npm run deploy-storybook-ci
